services:
  cinematch_database:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    
  cinematch_app:
    image: cinematch_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - cinematch_database
    env_file:
      - ./.env
  
volumes:
  pgdata: